<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ODZ23s\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ODZ23s/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5ODZ23s.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5ODZ23s\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5ODZ23s\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5ODZ23s',
    'container.build_id' => '17e73ff1',
    'container.build_time' => 1517237130,
));
